// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8UHd52iW6WZtuTIoMNKWI-PqCEfYNyc',
    appId: '1:1011917759398:ios:3ceabada403ff27e82e567',
    messagingSenderId: '1011917759398',
    projectId: 'hangingman-f44c7',
    storageBucket: 'hangingman-f44c7.firebasestorage.app',
    iosBundleId: 'icesi.edu.co.hangingMan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD8UHd52iW6WZtuTIoMNKWI-PqCEfYNyc',
    appId: '1:1011917759398:ios:3ceabada403ff27e82e567',
    messagingSenderId: '1011917759398',
    projectId: 'hangingman-f44c7',
    storageBucket: 'hangingman-f44c7.firebasestorage.app',
    iosBundleId: 'icesi.edu.co.hangingMan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRMEkB4zdI7P1bOvMXan-1YEPAO_lH_Q',
    appId: '1:1011917759398:web:247a1ebbf134003b82e567',
    messagingSenderId: '1011917759398',
    projectId: 'hangingman-f44c7',
    authDomain: 'hangingman-f44c7.firebaseapp.com',
    storageBucket: 'hangingman-f44c7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRMEkB4zdI7P1bOvMXan-1YEPAO_lH_Q',
    appId: '1:1011917759398:web:247a1ebbf134003b82e567',
    messagingSenderId: '1011917759398',
    projectId: 'hangingman-f44c7',
    authDomain: 'hangingman-f44c7.firebaseapp.com',
    storageBucket: 'hangingman-f44c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kI_yMvITKkplUSQkzLbCUdtk4aVCu50',
    appId: '1:1011917759398:android:ea95fed46b3897a482e567',
    messagingSenderId: '1011917759398',
    projectId: 'hangingman-f44c7',
    storageBucket: 'hangingman-f44c7.firebasestorage.app',
  );
}
